:global:
  componentName: rbac
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults

.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
